# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='joiners',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='organizer',
        ),
        migrations.AddField(
            model_name='plans',
            name='joined',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripsJoined', to='travelBuddy.Trips'),
        ),
        migrations.AddField(
            model_name='plans',
            name='organized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripsOrganized', to='travelBuddy.Users'),
        ),
    ]
