# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy', '0002_auto_20170927_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='organized',
        ),
        migrations.AddField(
            model_name='plans',
            name='join',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userJoin', to='travelBuddy.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='trip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tripPlan', to='travelBuddy.Trips'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='joined',
            field=models.ManyToManyField(through='travelBuddy.Plans', to='travelBuddy.Users'),
        ),
        migrations.AddField(
            model_name='trips',
            name='organized',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tripsOrganized', to='travelBuddy.Users'),
            preserve_default=False,
        ),
    ]
